RN-XI/Feature - New Task
rexnegotium/rexnegotium pull request #15
Opened 2019-09-18 21:45 UTC by ArchyGit

Added Create() method. Fixed readAll() formating.

2019-09-19 08:17 UTC, VasilyMartynov commented on RexNegotumOrganizerCore/src/com/rexnegotium/RexNegotiumAppStarter.java
> +        while (name == null) {
У тебя три цикла While. 
Наполнение немного отличается, но их можно ужать в один цикл вынесенный в функцию.
Посмотри как это можно сделать.

2019-09-19 08:17 UTC, VasilyMartynov commented on RexNegotumOrganizerCore/src/com/rexnegotium/RexNegotiumAppStarter.java
> +				beginDateTime = LocalDateTime.parse(dateString, Task.FORMATTER);
Проверки времени тоже можно вынести в отдельные функции.

2019-09-19 08:19 UTC, VasilyMartynov commented on RexNegotumOrganizerCore/src/com/rexnegotium/RexNegotiumAppStarter.java
> +		System.out.println("Вы хотите сделать задание любимым? Нажмите Y/N");
Хочу чтоб любимая задача отмечалась Звездочкой 🌟.

2019-09-19 08:21 UTC, IvanSenchukov commented on RexNegotumOrganizerCore/src/com/rexnegotium/RexNegotiumAppStarter.java
> +        while (name == null) {
У меня есть отдельные соображения, как собрать эту портянку в аккуратный класс. Пока можно не рефакторить.

2019-09-19 08:25 UTC, VasilyMartynov commented on RexNegotumOrganizerCore/src/module-info.java
> -/**
@IvanSenchukov Снеси файл в следующем апдейте мастера, ну или пофикси чтоб он не мешался.

2019-09-19 08:25 UTC, VasilyMartynov commented on RexNegotumOrganizerCore/src/com/rexnegotium/repository/inmemory/InMemoryTaskRepository.java
> -	public void refreshRepository() {
Функцию оставь, только положи её куда-то по структуре в подходящее место. 
Она пригодится для того чтобы при тестах наполнять Хранилище в памяти быстро.
Можешь украсить её добавив генерацию случайных строк и дат. Чтоб задания были не похожи.

Потмо пригодится для Автотестов.

2019-09-19 08:26 UTC, VasilyMartynov commented on RexNegotumOrganizerCore/src/com/rexnegotium/model/Task.java
> +        //return "Task { Note: " + note + '\'' + ", Task starts on: " +  beginDateTime.format(FORMATTER) + '\'' + ", Task ends on: " +  endDateTime.format(FORMATTER) + '\'' + ", task is favourite - "
Норм.
Старый код не бойся сносить чтоб не оставалась тонна комментов.

2019-09-19 08:34 UTC, VasilyMartynov commented on RexNegotumOrganizerCore/src/com/rexnegotium/controller/TaskController.java
> +import java.time.LocalDateTime;
Не критично, но лишние импорты тащить не обязательно.

2019-09-19 08:40 UTC, VasilyMartynov requested changes
Minor changes and improvements needed.

2019-09-20 14:25 UTC, ArchyGit commented on RexNegotumOrganizerCore/src/com/rexnegotium/RexNegotiumAppStarter.java
> +				beginDateTime = LocalDateTime.parse(dateString, Task.FORMATTER);
Вместе с глобальным рефакторингом

2019-09-23 15:07 UTC, VasilyMartynov commented on RexNegotumOrganizerCore/src/com/rexnegotium/RexNegotiumAppStarter.java
> +        while (name == null) {
Ок

2019-09-23 15:09 UTC, VasilyMartynov approved these changes

2019-09-23 15:09 UTC, merged