Добавлен метод Read()
rexnegotium/rexnegotium pull request #16
Opened 2019-10-01 20:21 UTC by ArchyGit

Добавлен метод Read. Требуется комментарий по поводу использования Exception и Catch. На два исключения один try/catch. Как это правильно делать/оформлять официально?

2019-10-02 10:34 UTC, VasilyMartynov commented on RexNegotumOrganizerCore/src/com/rexnegotium/repository/inmemory/InMemoryTaskRepository.java
> +	public Task findTaskById(Integer id) throws Exception {
Давай подумаем про Exception. @IvanSenchukov предлагает запилить, по классу Исключений для каждого слоя. Рисуй Задачу в issue для этого.

2019-10-02 10:35 UTC, VasilyMartynov commented on RexNegotumOrganizerCore/src/com/rexnegotium/service/TaskService.java
>  	 *obryvalka */
Мусор убрать.

2019-10-02 10:47 UTC, VasilyMartynov reviewed
@IvanSenchukov гляньи свои комменты оставь. Вроде всё Ок.

2019-10-02 10:47 UTC, VasilyMartynov commented on RexNegotumOrganizerCore/src/com/rexnegotium/RexNegotiumAppStarter.java
> +				if (!(beginDateTime.isAfter(LocalDateTime.now()) && beginDateTime.isBefore(endOfTime))) {
Здесь и ниже повторение в одну функциию вынести. 
Можно создать отдельный класс который работает с TUI (text user interface).
В нём сделать единую обработку Дат, Строк и Прочего.
Нарисуй себе задачу.

2019-10-02 10:47 UTC, VasilyMartynov commented on RexNegotumOrganizerCore/src/com/rexnegotium/RexNegotiumAppStarter.java
> +                if (idInput == null) {
|| idInput.isEmpty()
Я бы по вривычке добавил. Есть не Нулевые пустые строки солстоящие например из символа перноса каретки. \t \r просто пробелы например.

2019-10-02 10:47 UTC, VasilyMartynov commented on RexNegotumOrganizerCore/src/com/rexnegotium/RexNegotiumAppStarter.java
> +}
Снова пустая строка пропущена. В IDEA есть автоматическое применение "линтера" на выделенный текст CTRL+ALT+L (по умолчанию). Оно фиксит это и всякие глупости с форматированием.

2019-10-03 14:16 UTC, ArchyGit commented on RexNegotumOrganizerCore/src/com/rexnegotium/repository/inmemory/InMemoryTaskRepository.java
> +	public Task findTaskById(Integer id) throws Exception {
Создал новый таск, ожидаю ТЗ по нему. Как временное решение поправил текущую систему используя иерархию exception в try catch.

2019-10-03 14:20 UTC, ArchyGit commented on RexNegotumOrganizerCore/src/com/rexnegotium/RexNegotiumAppStarter.java
> +				if (!(beginDateTime.isAfter(LocalDateTime.now()) && beginDateTime.isBefore(endOfTime))) {
Вроде обговаривали что это при рефакторинге.

2019-10-03 20:54 UTC, VasilyMartynov commented on RexNegotumOrganizerCore/src/com/rexnegotium/repository/inmemory/InMemoryTaskRepository.java
> +        System.out.println("Task found...");
1) На этом этапе таск ещё не найден, он будет найден перед возвратом определённого таска из метода.
2) Слои приложения. Репозиторию не положено общаться с пользователем. Делать глупые принты и всё такое. Выноси в ближайший к слою взаимодействия с пользователем слой.

2019-10-03 21:24 UTC, VasilyMartynov requested changes
Ещё немного и я отстану со своими придирками.

2019-10-03 21:24 UTC, VasilyMartynov commented on RexNegotumOrganizerCore/src/com/rexnegotium/service/TaskService.java
>          return taskRepository.findTaskById(id);
Сколько Тасков будет найдено при старте приложения? - 0!
Придумай как сперва узнать стоит ли идти за тасками дальше или сказать пользователю что тасков нет, и искать нечего.

2019-10-03 21:24 UTC, VasilyMartynov commented on RexNegotumOrganizerCore/src/com/rexnegotium/RexNegotiumAppStarter.java
> -        }
Вот на этом вводе я агонизировал 5 или 7 попыток пока не вспомнил какой там конкретно ИД создаётся.
Предусмотреть выход из цикла мучения пользователя попыткой угадать ИД.
И в целом UI должен давать пользователю несколько вещей: понять где он сейчас, что делать дальше, и как вернуться назад и что при этом произойдёт. Необратимы операция следует Дублировать подтверждением.

2019-10-03 21:24 UTC, VasilyMartynov commented on RexNegotumOrganizerCore/src/com/rexnegotium/RexNegotiumAppStarter.java
> -        }
В принципе не стоит переживать. НО в следующей таске, с меню #18 лучше уже делать более внимательно.

2019-10-03 21:25 UTC, VasilyMartynov commented on RexNegotumOrganizerCore/src/com/rexnegotium/service/TaskService.java
>          return taskRepository.findTaskById(id);
Не обязательно это исправлять в текущем таске. А вот подумать обязательно.

2019-10-03 21:27 UTC, VasilyMartynov commented on RexNegotumOrganizerCore/src/com/rexnegotium/RexNegotiumAppStarter.java
> +				if (!(beginDateTime.isAfter(LocalDateTime.now()) && beginDateTime.isBefore(endOfTime))) {
Ок. В следующий раз буду придираться.

2019-10-03 21:28 UTC, VasilyMartynov commented on RexNegotumOrganizerCore/src/com/rexnegotium/repository/inmemory/InMemoryTaskRepository.java
> +	public Task findTaskById(Integer id) throws Exception {
Уехало в #17 .

2019-10-06 10:59 UTC, IvanSenchukov commented on RexNegotumOrganizerCore/src/com/rexnegotium/repository/inmemory/InMemoryTaskRepository.java
> +        System.out.println("Task found...");
Согласен - запись "Task found..." можно делать только после того, как действительно её нашёл. И поскольку System.out.println() выводит нам всё на экран - просто повесь // todo - логгировать нахождение таска.

2019-10-06 11:22 UTC, IvanSenchukov commented on RexNegotumOrganizerCore/src/com/rexnegotium/repository/inmemory/InMemoryTaskRepository.java
> +    }
К твоему вопросу - как вернуть таск в мейн - сейчас всё возвращается правильно - return foundTask возвращает таску в сервис, ретёрн из сервиса возвращает в контроллер, а контроллер возвращает в мэйн.

Ексепшн здесь бросать не надо - просто возвращай null. Эту ситуацию нужно обрабатывать на уровне выше.

Следующий момент связан с условием if ((foundTask == null) && !(foundTask.getId().equals(id)) && !(entryMap.containsKey(id))). Смотри, Java - штука оптимальная - если ты её заставишь проверять такое условие if (false && someVeryDifficultChecks()), она сразу вернёт тебе false. В самом деле - зачем делать сложную проверку, если при логическом И всё равно получится false.

Эта особенность используется при проверках на null очень часто. Например, может быть такое: if (foundTask != null && foundTask.getId() != null) // do something. В данном случае, если первая проверка проваливается, вторая не будет производиться. Если бы производилась вторая проверка, у нас возник бы наш любимый NullPointerException - потому что произошло бы что-то типа (null).getId()

Своим условием ты хотел проверить, наличие таска, который вытащили из хранилища, консистентность идентификатора таска с его идентификатором в хранилище (очень правильно) и того, есть ли идентификатор в списке ключей хранилища (это не нужно - если нет, мапа просто вернёт нам null, а это ты уже проверил). Чтобы твои условия отрабатывали правильно давай оформим условие в следующем виде
если ((таска не налл) И (айди не консистентен)) - бросаем ексепшн (накинь todo - тут должен быть брошен RepositoryException из другой задачи).

2019-10-09 15:08 UTC, IvanSenchukov requested changes

2019-10-09 15:08 UTC, IvanSenchukov commented on RexNegotumOrganizerCore/src/com/rexnegotium/RexNegotiumAppStarter.java
> +                idInput = null;
Тут следущие замечания - если у тебя что-то упало в процессе получения таска из репозитория (например, неконсистентный айдишник) или просто не найден таск, программа будет ожидать от нас приём очередного айдишника - что, в общем-то, не очень логично. Мы хотели найти конкретную таску по айдишнику, но ничего не нашли - вернулся null - нужно сообщить об этом пользователю и выйти из процесса.

Второй момент - я понял, что программа ожидает от нас айдишник ещё раз только потому, что видел код. Исправь это, пожалуйста. Вот скриншот.
![image](https://user-images.githubusercontent.com/28482108/66268490-84825700-e846-11e9-884c-6b186b755b6f.png)

2019-10-09 15:08 UTC, IvanSenchukov commented on RexNegotumOrganizerCore/src/com/rexnegotium/repository/inmemory/InMemoryTaskRepository.java
> +        return foundTask;
К твоему вопросу - как вернуть таск в мейн - сейчас всё возвращается правильно - return foundTask возвращает таску в сервис, ретёрн из сервиса возвращает в контроллер, а контроллер возвращает в мэйн.

Ексепшн здесь бросать не надо - просто возвращай null. Эту ситуацию нужно обрабатывать на уровне выше.

Следующий момент связан с условием if ((foundTask == null) && !(foundTask.getId().equals(id)) && !(entryMap.containsKey(id))). Смотри, Java - штука оптимальная - если ты её заставишь проверять такое условие if (false && someVeryDifficultChecks()), она сразу вернёт тебе false. В самом деле - зачем делать сложную проверку, если при логическом И всё равно получится false.

Эта особенность используется при проверках на null очень часто. Например, может быть такое: if (foundTask != null && foundTask.getId() != null) // do something. В данном случае, если первая проверка проваливается, вторая не будет производиться. Если бы производилась вторая проверка, у нас возник бы наш любимый NullPointerException - потому что произошло бы что-то типа (null).getId()

Своим условием ты хотел проверить, наличие таска, который вытащили из хранилища, консистентность идентификатора таска с его идентификатором в хранилище (очень правильно) и того, есть ли идентификатор в списке ключей хранилища (это не нужно - если нет, мапа просто вернёт нам null, а это ты уже проверил). Чтобы твои условия отрабатывали правильно давай оформим условие в следующем виде
если ((таска не налл) И (айди не консистентен)) - бросаем ексепшн (накинь todo - тут должен быть брошен RepositoryException из другой задачи).

2019-10-09 15:48 UTC, ArchyGit commented on RexNegotumOrganizerCore/src/com/rexnegotium/service/TaskService.java
>          return taskRepository.findTaskById(id);
Решили, что при выдаче null, будем говорить что тасков нет, предварительной проверки не будет.

2019-10-09 20:25 UTC, IvanSenchukov approved these changes

2019-10-09 20:25 UTC, merged